image: atlassian/default-image:4

pipelines:
  branches:
    staging:
      - step:
          name: Build Docker Images
          services:
            - docker
          caches:
            - docker-cache  
          script:
            - docker build -t admintadocker0428/admin_staging:frontend-${BITBUCKET_COMMIT:0:7} .
            - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
            - docker push admintadocker0428/admin_staging:frontend-${BITBUCKET_COMMIT:0:7}

      - step:
          name: Deploy to Staging
          deployment: staging
          services:
            - docker
          script:
            - pipe: atlassian/ssh-run:0.8.1
              variables:
                SSH_USER: "root"
                SERVER: "$STAGING_SERVER_IP"
                COMMAND: |
                  cd /root/deployment
                  FRONTEND_TAG=${BITBUCKET_COMMIT:0:7} docker-compose -f deployment.yml up -d frontend

definitions:
  services:
    docker:
      memory: 2048
  caches:
    docker-cache: /var/lib/docker